repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - '--autofix'
      - id: trailing-whitespace
        exclude: '.bumpversion.cfg'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: ruff-format
        # entry poetry run ...
        entry: ruff format pixi tests --config pyproject.toml

      - id: ruff
        # entry poetry run ...
        entry: ruff check pixi tests --fix --exit-non-zero-on-fix --show-fixes --config pyproject.toml
